version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  master:
    image: redis:latest
  slave:
    image: redis:latest
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master