FROM python:3.9-alpine3.13

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY . ./

RUN apk add gcc jq libc-dev


RUN jq -r '.default \
    | to_entries[]  \
    | .key + .value.version' \
    Pipfile.lock > requirements.txt && \
    jq -r '.develop \
    | to_entries[]  \
    | .key + .value.version' \
    Pipfile.lock > requirements.develop.txt && \
    pip install -r requirements.txt && \
    pip install -r requirements.develop.txt

ENV DOT_ENV=test
ENV TZ=UTC


CMD ["sh", "-c",  "pytest"]

