name: CI pipeline


on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: python

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pipenv install
      - name: Run tests
        run: |
          echo "done"

