name: CI pipeline


on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          jq -r '.default
          | to_entries[]
          | .key + .value.version' \
          Pipfile.lock > requirements.txt     
          pip install -r requirements.txt
      - name: Run tests
        run: |
          echo "done"

